### ISSUE TITLE
启动ChatWaifuServer.exe报错，显示缺少模型文件

### ISSUE THREAD

**Issue by birchtree2** [cjyaddone/ChatWaifuL2D#3]
报错信息如下:
```
ERROR (VoskAPI:Model():model.cc:122) Folder 'C:\Users\[我的用户名]\.cache\vosk\vosk-model-small-en-us-0.15.zip' does not contain model files. Make sure you specified the model path properly in Model constructor. If you are not sure about relative path, use absolute path specification.
Traceback (most recent call last):
  File "ChatWaifuServer.py", line 70, in <module>
  File "vosk\__init__.py", line 57, in __init__
    raise Exception("Failed to create a model")
Exception: Failed to create a model
[23620] Failed to execute script 'ChatWaifuServer' due to unhandled exception!
```
查看`.cache\vosk\vosk-model-small-en-us-0.15.zip`,显示压缩文件夹无效.

怀疑是未开启vpn导致的下载出错
ffmpeg已配置好

**Comment by cjyaddone** [comment]
是语音模型下载出错，可以考虑删除.cache\vosk\vosk-model-small-en-us-0.15.zip，挂上vpn重新打开server，会自动重新下载模型

**Comment by zhuhehuai** [comment]
> 
我也是同样的问题，删掉以后重连VPN，还是会遇到这个问题。

**Comment by zhuhehuai** [comment]
暂时解决了，是中文用户名导致的乱码问题。
按照报错的文件路径，新建文件夹，把下载好的模型放进去，就行了。一定要路径和报错的代码一样。

**Comment by HaoTian22** [comment]
他不走系统代理怎么办？我甚至用上tun他还是报错ssl证书错误

**Comment by zhengpeirong** [comment]
https://alphacephei.com/vosk/models
自己 重新 在这里下载吧
