### ISSUE TITLE
ChatGPT运行正常后，无法读取回答

### ISSUE THREAD

**Issue by MrChen-GH** [cjyaddone/ChatWaifuL2D#6]
设置为键盘输入
设置为日语输出
Question Received: 早上好
ChatGPT:
こんにちは。どういたしまして。どういたしましょうか？
Traceback (most recent call last):
  File "ChatWaifuServer.py", line 277, in <module>
  File "ChatWaifuServer.py", line 204, in generateSound
  File "scipy\io\wavfile.py", line 766, in write
PermissionError: [Errno 13] Permission denied: 'output.wav'
[11128] Failed to execute script 'ChatWaifuServer' due to unhandled exception!

**Comment by cjyaddone** [comment]
右键使用管理员权限执行server.exe

Sent from my iPhone

On Dec 25, 2022, at 02:55, MrChen-GH ***@***.***> wrote:

﻿

设置为键盘输入
设置为日语输出
Question Received: 早上好
ChatGPT:
こんにちは。どういたしまして。どういたしましょうか？
Traceback (most recent call last):
File "ChatWaifuServer.py", line 277, in
File "ChatWaifuServer.py", line 204, in generateSound
File "scipy\io\wavfile.py", line 766, in write
PermissionError: [Errno 13] Permission denied: 'output.wav'
[11128] Failed to execute script 'ChatWaifuServer' due to unhandled exception!

**Comment by MrChen-GH** [comment]
感谢，不过发现成功运行后无法切换L2D立绘
