### ISSUE TITLE
输入token后ChatWaifuServer报错

### ISSUE THREAD

**Issue by zhenban** [cjyaddone/ChatWaifuL2D#8]
Traceback (most recent call last):
  File "ChatWaifuServer.py", line 223, in <module>
  File "pyChatGPT\pyChatGPT.py", line 70, in __init__
  File "pyChatGPT\pyChatGPT.py", line 112, in __init_browser
  File "undetected_chromedriver\__init__.py", line 242, in __init__
  File "undetected_chromedriver\patcher.py", line 130, in auto
  File "undetected_chromedriver\patcher.py", line 166, in fetch_package
  File "urllib\request.py", line 280, in urlretrieve
urllib.error.ContentTooShortError: <urlopen error retrieval incomplete: got only 6885414 out of 6904173 bytes>
[27452] Failed to execute script 'ChatWaifuServer' due to unhandled exception!

**Comment by zhenban** [comment]
我错了我错了换了个梯子之后就解决了
